In [1]:
from PIL import Image, ImageDraw
import numpy as np
from enum import IntEnum
import world_object
from abc import ABC, abstractmethod
import random
import math

In [4]:
COLORS = {
    "red": '#FF000000',
    "green": '#00FF00',
    "blue": '#0000FF',
    "purple": '#A020F0',
    "yellow": '#FFFF00',
    "grey": '#808080',
}

SHAPES = {
    "TRIANGLE": Triangle,
    "SQUARE": Square,
    "CIRCLE": Circle,
    "RECTANGLE": Rectangle
}

# Map of object type to integers
OBJECT_TO_IDX = {
    "empty": 0,
    "agent": 1,
    "object":2,
    "goal": 8,
}

IDX_TO_OBJECT = {v: k for k, v in OBJECT_TO_IDX.items()}

# Map of agent direction indices to vectors
DIR_TO_VEC = [
    # Pointing right (positive X)
    np.array((1, 0)),
    # Down (positive Y)
    np.array((0, 1)),
    # Pointing left (negative X)
    np.array((-1, 0)),
    # Up (negative Y)
    np.array((0, -1)),
]

WIDTH = 200
HEIGHT = 200
GRID_SIZE = 20

In [5]:
class Actions(IntEnum):
    # Turn left, turn right, move forward
    left = 0
    right = 1
    forward = 2

In [63]:
class Shape:
    '''
        Attributes
        ----------
        distance_from_cooridinates : int
             How far the center should be from the points
        color : str
            A hex representation of the color that triangle should be
        fill : str
            Whether the object should be filled or not
            
        Methods
        -------
        init(self, size=int, color=str, fill=Bool, sound=None)
            Initializes the class
        draw(self, world=ImageDraw, x=int, y=int)
            Draws the triangle to the given Image at the x,y coordinates
        get_coordinates(self, x=int, y=int)
            Given a centerpoint, calculates the points of the triangle
    '''
    def __init__(self, size, color, fill = False, initial_loc = (-1,-1)):
        self.distance_from_coordinate = (size/2)
        self.color = color
        self.fill = fill
        self.row, self.col = initial_loc
        
    @abstractmethod
    def draw(self):
        pass
    
    @abstractmethod
    def get_coordinates():
        pass
        
class Triangle(Shape):
    def __init__(self, size, color, fill = False, initial_loc = (-1,-1)):
        Shape.__init__(self, size, color, fill, initial_loc)
        self.shape = "TRIANGLE"
    
    #Draw a triangle around this point
    def draw(self, world, x, y):
        ImageDraw.ink = self.color
        bottom_left,bottom_right,top = self.get_coordinates(x,y)
        world.polygon([bottom_left, bottom_right, top], self.color, outline="black")
        
    def get_coordinates(self, x, y):
        x1 = x - self.distance_from_coordinate
        x2 = x + self.distance_from_coordinate
        x3 = x
        y1 = y + self.distance_from_coordinate
        y2 = y + self.distance_from_coordinate
        y3 = y - self.distance_from_coordinate
        
        return (x1, y1), (x2, y2), (x3, y3)

class Rectangle(Shape):
    def __init__(self, size, color, fill = False, initial_loc = (-1, -1)):
        Shape.__init__(self, size, color, fill, initial_loc)
        self.shape = "RECTANGLE"
        
    #Draw a triangle around this point
    def draw(self, world, x, y):
        ImageDraw.ink = self.color
        top_left, bottom_right  = self.get_coordinates(x,y)

        world.rectangle([top_left, bottom_right], self.color, outline="black")
        
    def get_coordinates(self, x, y):
        height = self.distance_from_coordinate/2
        x1, y1 = x - self.distance_from_coordinate, y - height
        x2, y2 = x + self.distance_from_coordinate, y + height
        return (x1, y1), (x2, y2)

class Square(Shape):
    def __init__(self, size, color, fill = False, initial_loc = (-1, -1)):
        Shape.__init__(self, size, color, fill, initial_loc)
        self.shape = "SQUARE"
    
    def draw(self, world, x, y):
        ImageDraw.ink = self.color
        top_left, bottom_right = self.get_coordinates(x,y)
        world.rectangle([top_left, bottom_right], self.color, outline="black")
        
    def get_coordinates(self, x, y):
        x1, y1 = x - self.distance_from_coordinate, y - self.distance_from_coordinate
        x2, y2 = x + self.distance_from_coordinate, y + self.distance_from_coordinate
        return (x1, y1), (x2, y2)

class Circle(Shape):
    def __init__(self, size, color, fill = False, initial_loc = (-1, -1)):
        Shape.__init__(self, size, color, fill, initial_loc)
        self.shape = "CIRCLE"

    def draw(self, world, x, y):
        ImageDraw.ink = self.color
        bottom_left, top_right = self.get_coordinates(x,y)
        world.ellipse([bottom_left, top_right], fill = self.color, outline="black")
        
    def get_coordinates(self, x, y):
        x1, y1 = x - self.distance_from_coordinate, y - self.distance_from_coordinate
        x2, y2 = x + self.distance_from_coordinate, y + self.distance_from_coordinate
        return (x1, y1), (x2, y2) 

class Goal:
    def __init__(self, world, starting_loc = (-1, -1), shape = Square, color='#FFFF00'):
        self.world = world
        self.row, self.col = starting_loc
        self.shape = shape(HEIGHT, color)
        
    def update_loc(row, col):
        self.row = row
        self.col = col
            
    def draw(self, world, x, y):
        self.shape.draw(world, x, y)
    
class Agent:
    def __init__(self, world, starting_loc = (-1, -1), shape = Triangle, color='#FFFF00'):
        self.world = world
        self.row, self.col = starting_loc
        self.shape = shape(HEIGHT, color)
            
    def update_loc(row, col):
        self.row = row
        self.col = col
            
    def draw(self, world, x, y):
        self.shape.draw(world, x, y)
    
    
class GridWorld:
    '''
        This acts as our 2d world. Will handle logic of keeping objects in place
    '''
    def __init__(self, draw, size, background_color='#FFFFFF'):
        self.pencil = draw
        self.size = size
        self.x_offset = int(abs((WIDTH - size*GRID_SIZE)/2))
        self.y_offset = int(abs((HEIGHT - size*GRID_SIZE)/2))
        self.world = np.zeros(shape = (size, size))
        self.agent = Agent(self)
        self.goal = Goal(self)
        self.__setup_initial_locations()


        
    def __setup_initial_locations(self):
        #Makes min objects 1, so goal can be placed
        total_objects = math.floor((self.size**2)/3)
        agent_row, agent_col = self.__find_free_space('agent')
        goal = self.__find_free_space('goal')
        while total_objects > 0:
            row, col = self.__find_free_space('object')
            if row == -1 and col == -1:
                break
            else:
                total_objects -= 1
    
    def draw(self):
        step_size = GRID_SIZE 

        y_start = self.y_offset
        y_end = self.y_offset + (step_size*self.size)
        x_start = self.x_offset
        x_end = self.x_offset + (step_size*self.size)
        
        for x in range(y_start, y_end + 1, step_size):
            line = ((x, y_start), (x, y_end))
            self.pencil.line(line, fill=128)

        for y in range(x_start, x_end + 1, step_size):
            line = ((x_start, y), (x_end, y))
            self.pencil.line(line, fill=128)
        self.draw_objects()
        
        return image, step_size

    def draw_objects(self):
        for row in range(0, self.size):
            for col in range(0, self.size):
                world_object = self.world[row, col]
                if world_object == OBJECT_TO_IDX['object']:                    
                    shape, color = HelperMethods.get_random_unique_shape_and_color(self)
                    x, y = self.get_coordinates_from_array_loc(row, col)
                    print("Row: " + str(row) + " Col: " + str(col))
                    print("X: " + str(x) + " Y: " + str(y))

                    SHAPES[shape](GRID_SIZE/2, color).draw(self.pencil, x, y)
                
    def get_coordinates_from_array_loc(self, row, col):
        centroid = GRID_SIZE/2
        x = centroid + self.x_offset + (GRID_SIZE * row)
        y = centroid + self.y_offset + (GRID_SIZE * col)
        return x, y

    def __find_free_space(self, object_to_place):
        count = 0
        row, col = None, None
        while row is None and col is None or self.world[row, col] != 0:
            if count > self.size:
                return (-1, -1)
            row = random.randint(0, self.world.shape[0] - 1)
            col = random.randint(0, self.world.shape[1] - 1)
            count+=1
        self.world[row, col] = OBJECT_TO_IDX[object_to_place]
        return (row, col)
    
class HelperMethods:
    def get_random_color():
        return random.sample(list(COLORS), 1)[0]
    
    def get_random_shape():
        return random.sample(list(SHAPES), 1)[0]
        
    def get_random_unique_shape_and_color(world):
        agent_shape = world.agent.shape
        agent_color = world.agent.shape.color
        goal_shape = world.goal.shape
        goal_color = world.goal.shape.color
        
        random_shape = None
        random_color = None
        # Keep going until you have a unique shape/color that is not an agent or goal
        while (random_shape == None and random_color == None) or \
        (random_shape == agent_shape and random_color == agent_color) or \
        (random_shape == goal_shape and random_color == goal_color):
            random_shape = HelperMethods.get_random_shape()
            random_color = HelperMethods.get_random_color()
        return random_shape, random_color

In [62]:
image = Image.new(mode='RGB', size=(WIDTH, HEIGHT), color=(255,255,255, 0))
draw = ImageDraw.Draw(image)
world2 = GridWorld(draw, 4)
image, step_size = world2.draw()
print(world2.x_offset)
print(world2.world)
image.show()

Row: 0 Col: 3
X: 70.0 Y: 130.0
Row: 1 Col: 1
X: 90.0 Y: 90.0
Row: 3 Col: 0
X: 130.0 Y: 70.0
Row: 3 Col: 1
X: 130.0 Y: 90.0
Row: 3 Col: 2
X: 130.0 Y: 110.0
Row: 3 Col: 3
X: 130.0 Y: 130.0
60
[[0. 1. 0. 2.]
 [0. 2. 0. 0.]
 [0. 8. 0. 0.]
 [2. 2. 2. 2.]]


In [64]:
# Test objects are being drawn correctly
image = Image.new(mode='RGB', size=(WIDTH, HEIGHT), color=(255,255,255, 0))
draw = ImageDraw.Draw(image)

world = GridWorld(draw, 4)

image, step_size = world.draw()
size = step_size/2
draw = ImageDraw.Draw(image)

tri = Triangle(size, COLORS['yellow'])
tri.draw(draw, 90, 110)

circ = Circle(size, COLORS['blue'])
circ.draw(draw, 10, 10)

rec = Rectangle(size, COLORS['green'])
rec.draw(draw, 30, 30)

square = Square(size, COLORS['grey'])
square.draw(draw, 70, 70)

del draw

image.show()

Row: 0 Col: 1
X: 70.0 Y: 90.0
Row: 1 Col: 0
X: 90.0 Y: 70.0
Row: 2 Col: 1
X: 110.0 Y: 90.0
Row: 3 Col: 0
X: 130.0 Y: 70.0
Row: 3 Col: 2
X: 130.0 Y: 110.0


In [72]:
image3= Image.new(mode='RGB', size=(WIDTH, HEIGHT), color=(255,255,255, 0))
draw3 = ImageDraw.Draw(image3)
world3 = GridWorld(draw3, 4)
world3.draw()
world3.draw_objects()
image3.show()
image3.close()

Row: 0 Col: 0
X: 70.0 Y: 70.0
Row: 1 Col: 0
X: 90.0 Y: 70.0
Row: 2 Col: 0
X: 110.0 Y: 70.0
Row: 3 Col: 0
X: 130.0 Y: 70.0
Row: 3 Col: 3
X: 130.0 Y: 130.0
Row: 0 Col: 0
X: 70.0 Y: 70.0
Row: 1 Col: 0
X: 90.0 Y: 70.0
Row: 2 Col: 0
X: 110.0 Y: 70.0
Row: 3 Col: 0
X: 130.0 Y: 70.0
Row: 3 Col: 3
X: 130.0 Y: 130.0
